name = "Edonautics"
author = "Edomite"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6542663fb7d181d508e56f8a4b7c3a9e541c0a970921ff9e1b89886e043e3381"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
