name = "Edonautics"
author = "Edomite"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dab6292f6c74f7c75746a2c9f9f529cad92d795fb4a23635a1c29c71738df249"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
